#op : [func, [args, string=reg, num=reladdr], dest]
functable = {
        0x00 : ["nimp"],
        0x01 : ["nimp"],
        0x02 : ["nimp"],
        0x03 : ["nimp"],
        0x04 : ["nimp"],
        0x05 : ["nimp"],
        0x06 : ["nimp"],
        0x07 : ["nimp"],
        0x08 : ["nimp"],
        0x09 : ["nimp"],
        0x0a : ["nimp"],
        0x0b : ["nimp"],
        0x0c : ["nimp"],
        0x0d : ["nimp"],
        0x0e : ["nimp"],
        0x0f : ["nimp"],
        0x10 : ["nimp"],
        0x11 : ["nimp"],
        0x12 : ["nimp"],
        0x13 : ["nimp"],
        0x14 : ["nimp"],
        0x15 : ["nimp"],
        0x16 : ["nimp"],
        0x17 : ["nimp"],
        0x18 : ["nimp"],
        0x19 : ["nimp"],
        0x1a : ["nimp"],
        0x1b : ["nimp"],
        0x1c : ["nimp"],
        0x1d : ["nimp"],
        0x1e : ["nimp"],
        0x1f : ["nimp"],
        0x20 : ["nimp"],
        0x21 : ["nimp"],
        0x22 : ["nimp"],
        0x23 : ["nimp"],
        0x24 : ["nimp"],
        0x25 : ["nimp"],
        0x26 : ["nimp"],
        0x27 : ["nimp"],
        0x28 : ["nimp"],
        0x29 : ["nimp"],
        0x2a : ["nimp"],
        0x2b : ["nimp"],
        0x2c : ["nimp"],
        0x2d : ["nimp"],
        0x2e : ["nimp"],
        0x2f : ["nimp"],
        0x30 : ["nimp"],
        0x31 : ["nimp"],
        0x32 : ["nimp"],
        0x33 : ["nimp"],
        0x34 : ["nimp"],
        0x35 : ["nimp"],
        0x36 : ["nimp"],
        0x37 : ["nimp"],
        0x38 : ["nimp"],
        0x39 : ["nimp"],
        0x3a : ["nimp"],
        0x3b : ["nimp"],
        0x3c : ["nimp"],
        0x3d : ["nimp"],
        0x3e : ["nimp"],
        0x3f : ["nimp"],
        0x40 : ["nimp"],
        0x41 : ["nimp"],
        0x42 : ["nimp"],
        0x43 : ["nimp"],
        0x44 : ["nimp"],
        0x45 : ["nimp"],
        0x46 : ["nimp"],
        0x47 : ["nimp"],
        0x48 : ["nimp"],
        0x49 : ["nimp"],
        0x4a : ["nimp"],
        0x4b : ["nimp"],
        0x4c : ["nimp"],
        0x4d : ["nimp"],
        0x4e : ["nimp"],
        0x4f : ["nimp"],
        0x50 : ["nimp"],
        0x51 : ["nimp"],
        0x52 : ["nimp"],
        0x53 : ["nimp"],
        0x54 : ["nimp"],
        0x55 : ["nimp"],
        0x56 : ["nimp"],
        0x57 : ["nimp"],
        0x58 : ["nimp"],
        0x59 : ["nimp"],
        0x5a : ["nimp"],
        0x5b : ["nimp"],
        0x5c : ["nimp"],
        0x5d : ["nimp"],
        0x5e : ["nimp"],
        0x5f : ["nimp"],
        0x60 : ["nimp"],
        0x61 : ["nimp"],
        0x62 : ["nimp"],
        0x63 : ["nimp"],
        0x64 : ["nimp"],
        0x65 : ["nimp"],
        0x66 : ["nimp"],
        0x67 : ["nimp"],
        0x68 : ["nimp"],
        0x69 : ["nimp"],
        0x6a : ["nimp"],
        0x6b : ["nimp"],
        0x6c : ["nimp"],
        0x6d : ["nimp"],
        0x6e : ["nimp"],
        0x6f : ["nimp"],
        0x70 : ["nimp"],
        0x71 : ["nimp"],
        0x72 : ["nimp"],
        0x73 : ["nimp"],
        0x74 : ["nimp"],
        0x75 : ["nimp"],
        0x76 : ["nimp"],
        0x77 : ["nimp"],
        0x78 : ["nimp"],
        0x79 : ["nimp"],
        0x7a : ["nimp"],
        0x7b : ["nimp"],
        0x7c : ["nimp"],
        0x7d : ["nimp"],
        0x7e : ["nimp"],
        0x7f : ["nimp"],
        0x80 : ["add", ['a', 'b'], 'a'],
        0x81 : ["add", ['a', 'c'], 'a'],
        0x82 : ["add", ['a', 'd'], 'a'],
        0x83 : ["add", ['a', 'e'], 'a'],
        0x84 : ["add", ['a', 'h'], 'a'],
        0x85 : ["add", ['a', 'l'], 'a'],
        0x86 : ["nimp"],
        0x87 : ["add", ['a', 'a'], 'a'],
        0x88 : ["addc", ['a', 'b'], 'a'],
        0x89 : ["addc", ['a', 'c'], 'a'],
        0x8a : ["addc", ['a', 'd'], 'a'],
        0x8b : ["addc", ['a', 'e'], 'a'],
        0x8c : ["addc", ['a', 'h'], 'a'],
        0x8d : ["addc", ['a', 'l'], 'a'],
        0x8e : ["nimp"],
        0x8f : ["addc", ['a', 'a'], 'a'],
        0x90 : ["sub", ['a', 'b'], 'a'],
        0x91 : ["sub", ['a', 'c'], 'a'],
        0x92 : ["sub", ['a', 'd'], 'a'],
        0x93 : ["sub", ['a', 'e'], 'a'],
        0x94 : ["sub", ['a', 'h'], 'a'],
        0x95 : ["sub", ['a', 'l'], 'a'],
        0x96 : ["nimp"],
        0x97 : ["sub", ['a', 'a'], 'a'],
        0x98 : ["subc", ['a', 'b'], 'a'],
        0x99 : ["subc", ['a', 'c'], 'a'],
        0x9a : ["subc", ['a', 'd'], 'a'],
        0x9b : ["subc", ['a', 'e'], 'a'],
        0x9c : ["subc", ['a', 'h'], 'a'],
        0x9d : ["subc", ['a', 'l'], 'a'],
        0x9e : ["nimp"],
        0x9f : ["subc", ['a', 'a'], 'a'],
        0xa0 : ["and", ['a', 'b'], 'a'],
        0xa1 : ["and", ['a', 'c'], 'a'],
        0xa2 : ["and", ['a', 'd'], 'a'],
        0xa3 : ["and", ['a', 'e'], 'a'],
        0xa4 : ["and", ['a', 'h'], 'a'],
        0xa5 : ["and", ['a', 'l'], 'a'],
        0xa6 : ["nimp"],
        0xa7 : ["nimp"],
        0xa8 : ["nimp"],
        0xa9 : ["nimp"],
        0xaa : ["nimp"],
        0xab : ["nimp"],
        0xac : ["nimp"],
        0xad : ["nimp"],
        0xae : ["nimp"],
        0xaf : ["nimp"],
        0xb0 : ["or", ['a', 'b'], 'a'],
        0xb1 : ["or", ['a', 'c'], 'a'],
        0xb2 : ["or", ['a', 'd'], 'a'],
        0xb3 : ["or", ['a', 'e'], 'a'],
        0xb4 : ["or", ['a', 'h'], 'a'],
        0xb5 : ["or", ['a', 'l'], 'a'],
        0xb6 : ["nimp"],
        0xb7 : ["or", ['a', 'a'], 'a'],
        0xb8 : ["nimp"],
        0xb9 : ["nimp"],
        0xba : ["nimp"],
        0xbb : ["nimp"],
        0xbc : ["nimp"],
        0xbd : ["nimp"],
        0xbe : ["nimp"],
        0xbf : ["nimp"],
        0xc0 : ["nimp"],
        0xc1 : ["nimp"],
        0xc2 : ["nimp"],
        0xc3 : ["nimp"],
        0xc4 : ["nimp"],
        0xc5 : ["nimp"],
        0xc6 : ["nimp"],
        0xc7 : ["nimp"],
        0xc8 : ["nimp"],
        0xc9 : ["nimp"],
        0xca : ["nimp"],
        0xcb : ["nimp"],
        0xcc : ["nimp"],
        0xcd : ["nimp"],
        0xce : ["nimp"],
        0xcf : ["nimp"],
        0xd0 : ["nimp"],
        0xd1 : ["nimp"],
        0xd2 : ["nimp"],
        0xd3 : ["nimp"],
        0xd4 : ["nimp"],
        0xd5 : ["nimp"],
        0xd6 : ["nimp"],
        0xd7 : ["nimp"],
        0xd8 : ["nimp"],
        0xd9 : ["nimp"],
        0xda : ["nimp"],
        0xdb : ["nimp"],
        0xdc : ["nimp"],
        0xdd : ["nimp"],
        0xde : ["nimp"],
        0xdf : ["nimp"],
        0xe0 : ["nimp"],
        0xe1 : ["nimp"],
        0xe2 : ["nimp"],
        0xe3 : ["nimp"],
        0xe4 : ["nimp"],
        0xe5 : ["nimp"],
        0xe6 : ["nimp"],
        0xe7 : ["nimp"],
        0xe8 : ["nimp"],
        0xe9 : ["nimp"],
        0xea : ["nimp"],
        0xeb : ["nimp"],
        0xec : ["nimp"],
        0xed : ["nimp"],
        0xee : ["nimp"],
        0xef : ["nimp"],
        0xf0 : ["nimp"],
        0xf1 : ["nimp"],
        0xf2 : ["nimp"],
        0xf3 : ["nimp"],
        0xf4 : ["nimp"],
        0xf5 : ["nimp"],
        0xf6 : ["nimp"],
        0xf7 : ["nimp"],
        0xf8 : ["nimp"],
        0xf9 : ["nimp"],
        0xfa : ["nimp"],
        0xfb : ["nimp"],
        0xfc : ["nimp"],
        0xfd : ["nimp"],
        0xfe : ["nimp"],
        0xff : ["nimp"]
      }