#op : [func, [args, string=reg, num=reladdr], dest]
functable = {
        0x00 : ["nop"],
        0x01 : ["loadcn16", [1, 2], 'bc', 12],
        0x02 : ["nimp"],
        0x03 : ["inc16", ['bc'], 'bc', 8],
        0x04 : ["inc", ['b'], 'b'],
        0x05 : ["dec", ['b'], 'b'],
        0x06 : ["loadcn", [1], 'b', 8],
        0x07 : ["nimp"],
        0x08 : ["nimp"],
        0x09 : ["add", ['hl', 'bc'], 'hl', 8],
        0x0a : ["nimp"],
        0x0b : ["dec16", ['bc'], 'bc', 8],
        0x0c : ["inc", ['c'], 'c'],
        0x0d : ["dec", ['d'], 'd'],
        0x0e : ["loadcn", [1], 'c', 8],
        0x0f : ["nimp"],
        0x10 : ["nimp"],
        0x11 : ["loadcn16", [1, 2], 'de', 12],
        0x12 : ["nimp"],
        0x13 : ["inc16", ['de'], 'de', 8],
        0x14 : ["inc", ['d'], 'd'],
        0x15 : ["dec", ['d'], 'd'],
        0x16 : ["loadcn", [1], 'd', 8],
        0x17 : ["nimp"],
        0x18 : ["nimp"],
        0x19 : ["add", ['hl', 'de'], 'hl', 8],
        0x1a : ["nimp"],
        0x1b : ["dec16", ['de'], 'de', 8],
        0x1c : ["inc", ['e'], 'e'],
        0x1d : ["dec", ['e'], 'e'],
        0x1e : ["loadcn", [1], 'e', 8],
        0x1f : ["nimp"],
        0x20 : ["nimp"],
        0x21 : ["loadcn16", [1, 2], 'hl', 12],
        0x22 : ["nimp"],
        0x23 : ["inc16", ['hl'], 'hl', 8],
        0x24 : ["inc", ['h'], 'h'],
        0x25 : ["dec", ['h'], 'h'],
        0x26 : ["loadcn", [1], 'h', 8],
        0x27 : ["nimp"],
        0x28 : ["nimp"],
        0x29 : ["add", ['hl', 'hl'], 'hl', 8],
        0x2a : ["nimp"],
        0x2b : ["dec16", ['hl'], 'hl', 8],
        0x2c : ["inc", ['l'], 'l'],
        0x2d : ["dec", ['l'], 'l'],
        0x2e : ["loadcn", [1], 'l', 8],
        0x2f : ["nimp"],
        0x30 : ["nimp"],
        0x31 : ["loadcn16", [1, 2], 'sp', 12],
        0x32 : ["nimp"],
        0x33 : ["inc16", ['sp'], 'sp', 8],
        0x34 : ["nimp"],
        0x35 : ["nimp"],
        0x36 : ["nimp"],
        0x37 : ["nimp"],
        0x38 : ["nimp"],
        0x39 : ["add", ['sp', 'hl'], 'hl', 8],
        0x3a : ["nimp"],
        0x3b : ["dec16", ['sp'], 'sp', 8],
        0x3c : ["inc", ['a'], 'a'],
        0x3d : ["dec", ['a'], 'a'],
        0x3e : ["nimp"],
        0x3f : ["nimp"],
        0x40 : ["mov", ['b'], 'b', 4],
        0x41 : ["mov", ['c'], 'b', 4],
        0x42 : ["mov", ['d'], 'b', 4],
        0x43 : ["mov", ['e'], 'b', 4],
        0x44 : ["mov", ['h'], 'b', 4],
        0x45 : ["mov", ['l'], 'b', 4],
        0x46 : ["nimp"],
        0x47 : ["mov", ['a'], 'b', 4],
        0x48 : ["mov", ['b'], 'c', 4],
        0x49 : ["mov", ['c'], 'c', 4],
        0x4a : ["mov", ['d'], 'c', 4],
        0x4b : ["mov", ['e'], 'c', 4],
        0x4c : ["mov", ['h'], 'c', 4],
        0x4d : ["mov", ['l'], 'c', 4],
        0x4e : ["nimp"],
        0x4f : ["mov", ['a'], 'c', 4],
        0x50 : ["mov", ['b'], 'd', 4],
        0x51 : ["mov", ['c'], 'd', 4],
        0x52 : ["mov", ['d'], 'd', 4],
        0x53 : ["mov", ['e'], 'd', 4],
        0x54 : ["mov", ['h'], 'd', 4],
        0x55 : ["mov", ['l'], 'd', 4],
        0x56 : ["nimp"],
        0x57 : ["mov", ['b'], 'd', 4],
        0x58 : ["mov", ['b'], 'e', 4],
        0x59 : ["mov", ['c'], 'e', 4],
        0x5a : ["mov", ['d'], 'e', 4],
        0x5b : ["mov", ['e'], 'e', 4],
        0x5c : ["mov", ['h'], 'e', 4],
        0x5d : ["mov", ['l'], 'e', 4],
        0x5e : ["nimp"],
        0x5f : ["mov", ['b'], 'e', 4],
        0x60 : ["mov", ['b'], 'h', 4],
        0x61 : ["mov", ['c'], 'h', 4],
        0x62 : ["mov", ['d'], 'h', 4],
        0x63 : ["mov", ['e'], 'h', 4],
        0x64 : ["mov", ['h'], 'h', 4],
        0x65 : ["mov", ['l'], 'h', 4],
        0x66 : ["nimp"],
        0x67 : ["mov", ['b'], 'h', 4],
        0x68 : ["mov", ['b'], 'l', 4],
        0x69 : ["mov", ['c'], 'l', 4],
        0x6a : ["mov", ['d'], 'l', 4],
        0x6b : ["mov", ['e'], 'l', 4],
        0x6c : ["mov", ['h'], 'l', 4],
        0x6d : ["mov", ['l'], 'l', 4],
        0x6e : ["nimp"],
        0x6f : ["mov", ['b'], 'l', 4],
        0x70 : ["nimp"],
        0x71 : ["nimp"],
        0x72 : ["nimp"],
        0x73 : ["nimp"],
        0x74 : ["nimp"],
        0x75 : ["nimp"],
        0x76 : ["nimp"],
        0x77 : ["nimp"],
        0x78 : ["mov", ['b'], 'a', 4],
        0x79 : ["mov", ['c'], 'a', 4],
        0x7a : ["mov", ['d'], 'a', 4],
        0x7b : ["mov", ['e'], 'a', 4],
        0x7c : ["mov", ['h'], 'a', 4],
        0x7d : ["mov", ['l'], 'a', 4],
        0x7e : ["nimp"],
        0x7f : ["mov", ['a'], 'a', 4],
        0x80 : ["add", ['a', 'b'], 'a'],
        0x81 : ["add", ['a', 'c'], 'a'],
        0x82 : ["add", ['a', 'd'], 'a'],
        0x83 : ["add", ['a', 'e'], 'a'],
        0x84 : ["add", ['a', 'h'], 'a'],
        0x85 : ["add", ['a', 'l'], 'a'],
        0x86 : ["nimp"],
        0x87 : ["add", ['a', 'a'], 'a'],
        0x88 : ["addcr", ['a', 'b'], 'a'],
        0x89 : ["addcr", ['a', 'c'], 'a'],
        0x8a : ["addcr", ['a', 'd'], 'a'],
        0x8b : ["addcr", ['a', 'e'], 'a'],
        0x8c : ["addcr", ['a', 'h'], 'a'],
        0x8d : ["addcr", ['a', 'l'], 'a'],
        0x8e : ["nimp"],
        0x8f : ["addcr", ['a', 'a'], 'a'],
        0x90 : ["sub", ['a', 'b'], 'a'],
        0x91 : ["sub", ['a', 'c'], 'a'],
        0x92 : ["sub", ['a', 'd'], 'a'],
        0x93 : ["sub", ['a', 'e'], 'a'],
        0x94 : ["sub", ['a', 'h'], 'a'],
        0x95 : ["sub", ['a', 'l'], 'a'],
        0x96 : ["nimp"],
        0x97 : ["sub", ['a', 'a'], 'a'],
        0x98 : ["subc", ['a', 'b'], 'a'],
        0x99 : ["subc", ['a', 'c'], 'a'],
        0x9a : ["subc", ['a', 'd'], 'a'],
        0x9b : ["subc", ['a', 'e'], 'a'],
        0x9c : ["subc", ['a', 'h'], 'a'],
        0x9d : ["subc", ['a', 'l'], 'a'],
        0x9e : ["nimp"],
        0x9f : ["subc", ['a', 'a'], 'a'],
        0xa0 : ["and", ['a', 'b'], 'a'],
        0xa1 : ["and", ['a', 'c'], 'a'],
        0xa2 : ["and", ['a', 'd'], 'a'],
        0xa3 : ["and", ['a', 'e'], 'a'],
        0xa4 : ["and", ['a', 'h'], 'a'],
        0xa5 : ["and", ['a', 'l'], 'a'],
        0xa6 : ["nimp"],
        0xa7 : ["and", ['a', 'a'], 'a'],
        0xa8 : ["xor", ['a', 'b'], 'a'],
        0xa9 : ["xor", ['a', 'c'], 'a'],
        0xaa : ["xor", ['a', 'd'], 'a'],
        0xab : ["xor", ['a', 'e'], 'a'],
        0xac : ["xor", ['a', 'h'], 'a'],
        0xad : ["xor", ['a', 'l'], 'a'],
        0xae : ["nimp"],
        0xaf : ["xor", ['a', 'a'], 'a'],
        0xb0 : ["or", ['a', 'b'], 'a'],
        0xb1 : ["or", ['a', 'c'], 'a'],
        0xb2 : ["or", ['a', 'd'], 'a'],
        0xb3 : ["or", ['a', 'e'], 'a'],
        0xb4 : ["or", ['a', 'h'], 'a'],
        0xb5 : ["or", ['a', 'l'], 'a'],
        0xb6 : ["nimp"],
        0xb7 : ["or", ['a', 'a'], 'a'],
        0xb8 : ["sub", ['a', 'b'], None], #CP
        0xb9 : ["sub", ['a', 'c'], None], #CP
        0xba : ["sub", ['a', 'd'], None], #CP
        0xbb : ["sub", ['a', 'e'], None], #CP
        0xbc : ["sub", ['a', 'h'], None], #CP
        0xbd : ["sub", ['a', 'l'], None], #CP
        0xbe : ["nimp"],
        0xbf : ["nimp"],
        0xc0 : ["nimp"],
        0xc1 : ["nimp"],
        0xc2 : ["nimp"],
        0xc3 : ["nimp"],
        0xc4 : ["nimp"],
        0xc5 : ["nimp"],
        0xc6 : ["nimp"],
        0xc7 : ["nimp"],
        0xc8 : ["nimp"],
        0xc9 : ["nimp"],
        0xca : ["nimp"],
        0xcb : ["nimp"],
        0xcc : ["nimp"],
        0xcd : ["nimp"],
        0xce : ["nimp"],
        0xcf : ["nimp"],
        0xd0 : ["nimp"],
        0xd1 : ["nimp"],
        0xd2 : ["nimp"],
        0xd3 : ["nimp"],
        0xd4 : ["nimp"],
        0xd5 : ["nimp"],
        0xd6 : ["nimp"],
        0xd7 : ["nimp"],
        0xd8 : ["nimp"],
        0xd9 : ["nimp"],
        0xda : ["nimp"],
        0xdb : ["nimp"],
        0xdc : ["nimp"],
        0xdd : ["nimp"],
        0xde : ["nimp"],
        0xdf : ["nimp"],
        0xe0 : ["nimp"],
        0xe1 : ["nimp"],
        0xe2 : ["nimp"],
        0xe3 : ["nimp"],
        0xe4 : ["nimp"],
        0xe5 : ["nimp"],
        0xe6 : ["nimp"],
        0xe7 : ["nimp"],
        0xe8 : ["addcn", ['sp', 1], 'sp', 16],
        0xe9 : ["nimp"],
        0xea : ["nimp"],
        0xeb : ["nimp"],
        0xec : ["nimp"],
        0xed : ["nimp"],
        0xee : ["nimp"],
        0xef : ["nimp"],
        0xf0 : ["nimp"],
        0xf1 : ["nimp"],
        0xf2 : ["nimp"],
        0xf3 : ["nimp"],
        0xf4 : ["nimp"],
        0xf5 : ["nimp"],
        0xf6 : ["nimp"],
        0xf7 : ["nimp"],
        0xf8 : ["nimp"],
        0xf9 : ["load", ['hl'], 'sp', 8],
        0xfa : ["nimp"],
        0xfb : ["nimp"],
        0xfc : ["nimp"],
        0xfd : ["nimp"],
        0xfe : ["nimp"],
        0xff : ["nimp"]
      }